name: Pipeline Calculadora

on:
  push:
    branches:
      - main

jobs:

  teste-soma:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Instalar Jest
        run: npm install -g jest

      - name: Testar soma
        run: jest calculadora.test.js -t "soma" --config='{}'


  teste-subtracao:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Instalar Jest
        run: npm install -g jest

      - name: Testar subtração
        run: jest calculadora.test.js -t "subtracao" --config='{}'


  teste-multiplicacao:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Instalar Jest
        run: npm install -g jest

      - name: Testar multiplicação
        run: jest calculadora.test.js -t "multiplicacao" --config='{}'


  teste-divisao:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Instalar Jest
        run: npm install -g jest

      - name: Testar divisão
        run: jest calculadora.test.js -t "divisao" --config='{}'


  deploy:
    runs-on: ubuntu-latest

    needs:
      - teste-soma
      - teste-subtracao
      - teste-multiplicacao
      - teste-divisao

    steps:
      - name: Deploy
        run: echo "Todos os testes passaram. Fazendo deploy..."